import torch

from cs336_basics.checkpoints import load_checkpoint
from cs336_basics.funcs import pick_best_device
from cs336_basics.tokenizer import Tokenizer
from cs336_basics.transformer import TransformerLM


class Decoder:
    _model: TransformerLM
    _tokenizer: Tokenizer
    _end_token_id: int

    def __init__(self, model: TransformerLM, tokenizer: Tokenizer, end_token="<|endoftext|>"):
        """Decoder class that is given a pre-initialized model and tokenizer."""
        self._model = model
        self._tokenizer = tokenizer
        end_token_id = tokenizer.get_token_id(end_token.encode("utf-8"))
        if end_token_id is None:
            raise ValueError(f"Can't find {end_token} in tokenizer's vocab")
        else:
            self._end_token_id = end_token_id

    def generate_completions(self, input: str, max_tokens: int) -> str:
        """Generate completions for the given input until max_tokens is hit, our context window is hit,
        or a special end token is emitted.

        Returns only the new text generated by the model - does not return input again."""
        input_tokens = self._tokenizer.encode(input)
        if len(input_tokens) > self._model.context_length - 1:
            raise ValueError(f"Input is {len(input_tokens)} but our max context length is {self._model.context_length}")

        # Create a tensor of all zeroes with the full context length, then copy our tokens into it
        # We can slice the tensor when passing into the model to the right size - but this way we aren't
        # constantly trying to expand the tensor as our input grows. The extra mem cost should be pretty minimal
        # since it's just a long list of int64s.
        input_tensor = torch.zeros((1, self._model.context_length), dtype=torch.int64, device=self._model.device)
        input_tensor[0][: len(input_tokens)] = torch.tensor(input_tokens)

        original_len = len(input_tokens)
        input_tokens_used = len(input_tokens)
        last_token = -1
        self._model.eval()
        with torch.no_grad():
            while (
                len(input_tokens) < self._model.context_length - 1
                and last_token != self._end_token_id
                and len(input_tokens) - original_len < max_tokens
            ):
                to_predict = input_tensor[:, :input_tokens_used]
                print(f"Predicting {to_predict}")
                prediction = self._model(to_predict)

                logits = prediction[0][-1]
                print(f"Logits: {logits}")
                # For now assume temp = 0
                last_token_tensor = torch.argmax(logits)
                print(f"Last token tensor: {last_token_tensor}")

                input_tensor[0][input_tokens_used] = last_token_tensor
                input_tokens_used += 1
                last_token = last_token_tensor.item()

        all_tokens = input_tensor[0, :input_tokens_used].tolist()
        return self._tokenizer.decode(all_tokens)


if __name__ == "__main__":
    dev = pick_best_device()

    # todo - this should really be saved with checkpoint
    model = TransformerLM(
        vocab_size=10000,
        num_transformer_layers=4,
        d_model=512,
        num_heads=16,
        d_ff=1344,
        max_seq_len=256,
        theta=10000.0,
        device=dev,
        dtype=torch.float32,
    )

    load_checkpoint(
        "/Users/eogren/src/assignment1-basics/checkpoints/tinystories-best.pt", model, None, device_override=dev
    )

    tokenizer = Tokenizer.from_files(
        "/Users/eogren/src/assignment1-basics/trained_tokenizers/tinystories_10k.vocab.json",
        "/Users/eogren/src/assignment1-basics/trained_tokenizers/tinystories_10k_merge.json",
    )

    decoder = Decoder(model, tokenizer)
    print(decoder.generate_completions("One night,", 200))
